name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests.py

  docker_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v3
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          

      - name: Build Docker image
        run: |
          docker build -t url-shortener .

      - name: Tag Docker image
        run: |
          docker tag url-shortener ${{ secrets.DOCKER_USERNAME }}/url-shortener:latest

      - name: Push Docker image
        run: |
          docker
       # New job: Security scan with OWASP ZAP

  vulnerability_scan:
      runs-on: ubuntu-latest
      needs: docker_build

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Snyk CLI
          run: |
            npm install -g snyk

        - name: Authenticate Snyk
          run: snyk auth ${{ secrets.SNYK_TOKEN }}

        - name: Run Snyk vulnerability scan
          run: snyk test --file=requirements.txt --severity-threshold=high